# Generated by Django 5.2.6 on 2025-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("professional", "Professionnel"),
                    ("individual", "Particulier"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
    ]
