# pylint: skip-file
# Generated by Django 5.2.6 on 2025-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_service_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField()),
                ("photo", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, related_name="workshops", to="accounts.service"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
