# Generated by Django 5.2.6 on 2025-09-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_workshop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="city",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="workshop",
            name="professionals",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "professional"},
                related_name="professional_workshops",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
