# pylint: skip-file
# Generated by Django 5.2.6 on 2025-09-21 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_service_created_by_workshop_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="city",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
    ]
