# pylint: disable=invalid-name
"""Update verbose names and ordering for planner models."""

# Generated by Django 5.2.6 on 2025-11-03 19:04

from django.db import migrations


class Migration(migrations.Migration):
    """Migration for adjusting planner model metadata."""
    dependencies = [
        ("accounts", "0007_seed_calendar_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendar",
            options={
                "ordering": ["owner__id", "name"],
                "verbose_name": "calendar",
                "verbose_name_plural": "calendars",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_at"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="eventattendee",
            options={
                "verbose_name": "event attendee",
                "verbose_name_plural": "event attendees",
            },
        ),
    ]
